
import { Service, ServiceCategory } from './types';

export const SERVICES: Service[] = [
  // --- NGO & SOCIAL SECTOR ---
  {
    id: 'ngo-trust',
    name: 'Trust Registration',
    category: ServiceCategory.NGO,
    shortDescription: 'Form a Charitable Trust under the Indian Trust Act.',
    description: 'Expert drafting and registration of Trust Deeds at the Sub-Registrar office. Ideal for family-run social initiatives and asset management for charitable causes.',
    price: '7,500',
    rating: 4.9,
    reviews: 1240,
    image: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&q=100&w=1200',
    features: ['Deed Drafting by Experts', 'Liaison with Sub-Registrar', 'PAN/TAN Filing Included'],
    documents: ['ID Proofs of Settlor/Trustees', 'Address Proofs', 'Trust Deed (Draft)', 'NOC for Office'],
    process: ['Drafting', 'Stamp Duty Payment', 'Registrar Appointment', 'Approval'],
    timeframe: '15 Days',
    validity: 'Lifetime',
    faqs: []
  },
  {
    id: 'ngo-society',
    name: 'Society Registration',
    category: ServiceCategory.NGO,
    shortDescription: 'State-level Society formation for clubs and welfare associations.',
    description: 'Register under the Societies Registration Act, 1860. Suitable for democratic member-based organizations and state-level social operations.',
    price: '9,500',
    rating: 4.8,
    reviews: 850,
    image: 'https://images.unsplash.com/photo-1577412647305-991150c7d163?auto=format&fit=crop&q=100&w=1200',
    features: ['Bye-laws Drafting', 'Governing Body Formation', 'State Filing Assistance'],
    documents: ['7 Member IDs', 'MoA & Bye-laws', 'Address Proof'],
    process: ['Drafting', 'Filing with ROS', 'Verification', 'Certificate'],
    timeframe: '30-45 Days',
    validity: 'Annual/Lifetime (varies by state)',
    faqs: []
  },
  {
    id: 'section-8',
    name: 'Section 8 Company',
    category: ServiceCategory.NGO,
    shortDescription: 'Premium NGO structure under MCA (Non-Profit Company).',
    description: 'The most prestigious NGO structure in India. Operates as a Limited Company without profit distribution. High credibility for international funding and CSR.',
    price: '18,000',
    rating: 4.9,
    reviews: 2100,
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=100&w=1200',
    features: ['MCA License Application', '2 DIN & DSC Included', 'Expert MoA/AoA Drafting'],
    documents: ['2 Director IDs', 'Digital Signatures', 'Utility Bill for Office'],
    process: ['Name Reservation', 'MCA License Approval', 'Incorporation'],
    timeframe: '20 Days',
    validity: 'Lifetime',
    faqs: []
  },
  {
    id: '12a-80g',
    name: '12A & 80G Registration',
    category: ServiceCategory.NGO,
    shortDescription: '100% Tax Exemption for NGO & Donor Benefits.',
    description: 'Crucial for tax-free income and enabling donors to claim 50% deductions. Mandatory for eligibility for CSR funds from top corporates.',
    price: '15,000',
    rating: 4.9,
    reviews: 4450,
    image: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&q=100&w=1200',
    features: ['Form 10A Preparation', 'Direct IT Dept Liaison', '5 Year Provisional Approval'],
    documents: ['Registration Cert', 'Trust Deed', '3 Year Audits (if applicable)'],
    process: ['Online Application', 'Query Management', 'Final Order Issuance'],
    timeframe: '60 Days',
    validity: '5 Years',
    faqs: []
  },
  {
    id: 'csr-1',
    name: 'CSR-1 Registration',
    category: ServiceCategory.NGO,
    shortDescription: 'Mandatory to accept Corporate CSR Funds.',
    description: 'Registration with MCA to become eligible for Corporate Social Responsibility funding from companies under Section 135.',
    price: '4,500',
    rating: 4.8,
    reviews: 1100,
    image: 'https://images.unsplash.com/photo-1554224154-26032ffc0d07?auto=format&fit=crop&q=100&w=1200',
    features: ['MCA Form CSR-1 Filing', 'Instant Certificate Generation', 'Compliance Audit'],
    documents: ['12A/80G Certificates', 'Director PAN', 'Registration Doc'],
    process: ['Filing Form', 'System Approval'],
    timeframe: '3 Days',
    validity: 'Lifetime',
    faqs: []
  },
  {
    id: 'fcra-reg',
    name: 'FCRA Registration',
    category: ServiceCategory.NGO,
    shortDescription: 'Accept Foreign Funding via MHA.',
    description: 'Official license from the Ministry of Home Affairs required for any NGO to receive donations from international sources.',
    price: '25,000',
    rating: 4.7,
    reviews: 320,
    image: 'https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?auto=format&fit=crop&q=100&w=1200',
    features: ['MHA Portal Filing', 'Intelligence Bureau (IB) Support', 'Audit Compliance'],
    documents: ['3 Year Balance Sheets', 'Activity Report', 'Detailed Trustee Profiles'],
    process: ['Application submission', 'IB Verification', 'Ministry Approval'],
    timeframe: '180 Days',
    validity: '5 Years',
    faqs: []
  },
  {
    id: 'niti-aayog',
    name: 'NITI Aayog (NGO Darpan)',
    category: ServiceCategory.NGO,
    shortDescription: 'Enlist with Central Govt Portal for Grants.',
    description: 'Mandatory registration for applying to Central or State Government schemes, grants, and subsidies in India.',
    price: '2,500',
    rating: 4.9,
    reviews: 5100,
    image: 'https://images.unsplash.com/photo-1532629345422-7515f3d16bb8?auto=format&fit=crop&q=100&w=1200',
    features: ['Unique ID Generation', 'Scheme Mapping', 'Profile Verification'],
    documents: ['NGO PAN', 'Trustee Adhaar', 'Registration Details'],
    process: ['Portal Signup', 'Data Validation', 'Verification'],
    timeframe: '5 Days',
    validity: 'Lifetime',
    faqs: []
  },

  // --- CORPORATE & STARTUP ---
  {
    id: 'pvt-ltd',
    name: 'Private Limited Company',
    category: ServiceCategory.CORPORATE,
    shortDescription: 'Premium Startup Incorporation with MCA.',
    description: 'The preferred legal entity for high-growth startups and businesses looking for investment and formal structure.',
    price: '12,000',
    rating: 4.9,
    reviews: 6200,
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&q=100&w=1200',
    features: ['2 DSC & DIN Included', 'Company Name Approval', 'MoA/AoA Custom Drafting'],
    documents: ['ID & Address Proofs', 'Bank Statement', 'Office Proof'],
    process: ['DSC Generation', 'SPICe+ Filing', 'COI Issuance'],
    timeframe: '10 Days',
    validity: 'Lifetime',
    faqs: []
  },
  {
    id: 'llp-reg',
    name: 'LLP Registration',
    category: ServiceCategory.CORPORATE,
    shortDescription: 'Hybrid of Company & Partnership.',
    description: 'Offers limited liability with the flexible internal structure of a partnership. Low compliance compared to Pvt Ltd.',
    price: '9,000',
    rating: 4.8,
    reviews: 3100,
    image: 'https://images.unsplash.com/photo-1454165833767-0274b0026739?auto=format&fit=crop&q=100&w=1200',
    features: ['LLP Agreement Drafting', 'Partner DSC Registration', 'ROC Filing'],
    documents: ['Partner IDs', 'Utility Bill', 'NOC'],
    process: ['Name Approval', 'Incorporation', 'Agreement Filing'],
    timeframe: '15 Days',
    validity: 'Lifetime',
    faqs: []
  },
  {
    id: 'opc-reg',
    name: 'One Person Company (OPC)',
    category: ServiceCategory.CORPORATE,
    shortDescription: 'Company structure for Solo Founders.',
    description: 'Combining solo control with a corporate identity. Best for individual professionals and solo entrepreneurs.',
    price: '11,000',
    rating: 4.9,
    reviews: 1800,
    image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&q=100&w=1200',
    features: ['Solo Ownership Control', 'Limited Liability', 'Easy Scalability'],
    documents: ['Founder ID', 'Nominee ID', 'Office Docs'],
    process: ['DSC/DIN', 'Application Filing', 'Approval'],
    timeframe: '10 Days',
    validity: 'Lifetime',
    faqs: []
  },
  {
    id: 'nidhi-company',
    name: 'Nidhi Company Setup',
    category: ServiceCategory.CORPORATE,
    shortDescription: 'Mutual benefit society for internal lending.',
    description: 'A non-banking financial entity specifically for fostering savings and providing credit among members.',
    price: '35,000',
    rating: 4.6,
    reviews: 240,
    image: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&q=100&w=1200',
    features: ['Full MCA Compliance', 'Drafting Assistance', 'Banking Policy Plan'],
    documents: ['7 Members PAN', '3 Directors ID', 'Office NOC'],
    process: ['Name Approval', 'MoA/AoA', 'Certificate'],
    timeframe: '30 Days',
    validity: 'Lifetime',
    faqs: []
  },

  // --- GOVT LICENSES ---
  {
    id: 'gst-reg',
    name: 'GST Registration',
    category: ServiceCategory.LICENSE,
    shortDescription: 'Mandatory Tax ID for Business.',
    description: 'Legal authorization to participate in the Goods and Services Tax system. Essential for inter-state billing.',
    price: '1,500',
    rating: 4.9,
    reviews: 12000,
    image: 'https://images.unsplash.com/photo-1554224155-1696413575b9?auto=format&fit=crop&q=100&w=1200',
    features: ['HSN Code Advisory', 'Portal Setup', 'Compliance Liaison'],
    documents: ['PAN & Aadhar', 'Address Proof', 'Photo'],
    process: ['Online Form filing', 'Officer Verification', 'Certificate'],
    timeframe: '7 Days',
    validity: 'Lifetime',
    faqs: []
  },
  {
    id: 'msme-reg',
    name: 'MSME (Udyam) Registration',
    category: ServiceCategory.LICENSE,
    shortDescription: 'Priority Sector Benefits for SME.',
    description: 'Government certification to unlock low-interest bank loans, subsidies, and priority in government procurement.',
    price: '1,000',
    rating: 4.9,
    reviews: 8900,
    image: 'https://images.unsplash.com/photo-1664575602554-2087b04935a5?auto=format&fit=crop&q=100&w=1200',
    features: ['Instant E-Certificate', 'Government Subsidy Eligibility', 'SME Benefits'],
    documents: ['Aadhar Linked with Mobile', 'PAN'],
    process: ['Portal Submission', 'OTP Verification'],
    timeframe: '1 Day',
    validity: 'Lifetime',
    faqs: []
  },
  {
    id: 'fssai-lic',
    name: 'FSSAI (Food License)',
    category: ServiceCategory.LICENSE,
    shortDescription: 'Mandatory for all Food Businesses.',
    description: 'Ensures food safety standards. Mandatory for anyone handling food products, from manufacturers to retailers.',
    price: '3,000',
    rating: 4.8,
    reviews: 4500,
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&q=100&w=1200',
    features: ['Safety Plan Support', 'State/Central License Check', 'Renewal Reminders'],
    documents: ['Business Photo', 'Premises Proof', 'Food Category List'],
    process: ['Form selection', 'Online Filing', 'Inspection (if req)', 'Issuance'],
    timeframe: '15 Days',
    validity: '5 Years',
    faqs: []
  },
  {
    id: 'tm-reg',
    name: 'Trademark Registration',
    category: ServiceCategory.IPR,
    shortDescription: 'Protect your Brand Name & Logo.',
    description: 'Secure legal ownership of your identity. Use (TM) immediately after filing and (R) after registration.',
    price: '3,500',
    rating: 4.9,
    reviews: 7800,
    image: 'https://images.unsplash.com/photo-1589254065878-42c9da997008?auto=format&fit=crop&q=100&w=1200',
    features: ['Brand Search Report', 'Class Identification', 'Objection Replies'],
    documents: ['Logo File', 'Power of Attorney', 'Affidavit'],
    process: ['Trademark Search', 'Application Filing', 'Examination'],
    timeframe: '12 Months',
    validity: '10 Years',
    faqs: []
  },
  {
    id: 'ngo-website',
    name: 'NGO Impact Website',
    category: ServiceCategory.TECH,
    shortDescription: 'HD Website with Donation Gateway.',
    description: 'A powerful digital tool designed specifically for social impact. Includes recurring donation modules.',
    price: '12,500',
    rating: 4.9,
    reviews: 840,
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&q=100&w=1200',
    features: ['Payment Gateway (UPI/CC)', 'Mobile-First Design', 'SEO Support'],
    documents: ['Brand Assets', 'Mission Statement', 'Team Photos'],
    process: ['Design Sprint', 'Development', 'Final Launch'],
    timeframe: '15 Days',
    validity: 'Annual Renewal',
    faqs: []
  },
  {
    id: 'legal-advisory',
    name: 'Elite Legal Advisory',
    category: ServiceCategory.OTHER,
    shortDescription: 'Direct Consultation with Advocate Tamanna.',
    description: 'High-level legal strategy, contract drafting, and litigation consultation for complex organizational needs.',
    price: '5,000',
    rating: 4.9,
    reviews: 1500,
    image: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&q=100&w=1200',
    features: ['Zoom Consultation', 'Legal Opinion Paper', 'Strategy Deck'],
    documents: ['Case History', 'Relevant Contracts'],
    process: ['Case Review', 'Scheduling Call', 'Opinion Delivery'],
    timeframe: 'Flexible',
    validity: 'Project Based',
    faqs: []
  }
];

export const CATEGORIES = Object.values(ServiceCategory);
