
import { Service, ServiceCategory } from './types';

export const SERVICES: Service[] = [
  // --- NGO & SOCIAL SECTOR ---
  {
    id: 'ngo-trust',
    name: 'Trust Registration',
    category: ServiceCategory.NGO,
    shortDescription: 'Form a Charitable Trust under the Indian Trust Act.',
    description: 'Expert drafting and registration of Trust Deeds at the Sub-Registrar office. Ideal for small to medium social initiatives.',
    price: '7,500',
    rating: 4.9,
    reviews: 1240,
    image: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&q=100&w=1200',
    features: ['Deed Drafting', 'Liaison with Registrar', 'PAN/TAN Included'],
    documents: ['ID Proofs', 'Address Proofs', '2 Witnesses', 'NOC for Office'],
    process: ['Drafting', 'Stamp Duty', 'Registrar Meeting', 'Approval'],
    timeframe: '15 Days',
    validity: 'Lifetime',
    faqs: []
  },
  {
    id: 'ngo-society',
    name: 'Society Registration',
    category: ServiceCategory.NGO,
    shortDescription: 'State-level Society formation for clubs and associations.',
    description: 'Register under the Societies Registration Act, 1860. Suitable for member-based organizations and state-level operations.',
    price: '9,500',
    rating: 4.8,
    reviews: 850,
    image: 'https://images.unsplash.com/photo-1577412647305-991150c7d163?auto=format&fit=crop&q=100&w=1200',
    features: ['Bye-laws Drafting', 'Member List Prep', 'State Filing'],
    documents: ['7 Member IDs', 'MoA', 'Bye-laws', 'Office Proof'],
    process: ['Drafting', 'Filing with ROS', 'Inquiry', 'Certificate'],
    timeframe: '30-45 Days',
    validity: 'Annual/Lifetime',
    faqs: []
  },
  {
    id: 'section-8',
    name: 'Section 8 Company',
    category: ServiceCategory.NGO,
    shortDescription: 'Premium NGO structure under MCA (Non-Profit Company).',
    description: 'The most prestigious NGO structure in India. Operates as a Limited Company without profit motive. High credibility for CSR.',
    price: '18,000',
    rating: 4.9,
    reviews: 2100,
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=100&w=1200',
    features: ['MCA License', 'DIN/DSC Included', 'MoA/AoA Prep'],
    documents: ['2 Director IDs', 'Digital Signatures', 'Address Proof'],
    process: ['Name Reservation', 'License App', 'Incorporation'],
    timeframe: '20 Days',
    validity: 'Lifetime',
    faqs: []
  },
  {
    id: '12a-80g',
    name: '12A & 80G Registration',
    category: ServiceCategory.NGO,
    shortDescription: '100% Tax Exemption for NGO & Donor Benefits.',
    description: 'Mandatory for tax-free income and enabling donors to claim 50% deductions. Crucial for CSR funds.',
    price: '15,000',
    rating: 4.9,
    reviews: 4450,
    image: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&q=100&w=1200',
    features: ['Form 10A Filing', 'Department Liaison', '5 Year Approval'],
    documents: ['Registration Certificate', 'Trust Deed', '3 Year Audit'],
    process: ['Online Filing', 'Query Reply', 'Final Order'],
    timeframe: '60 Days',
    validity: '5 Years',
    faqs: []
  },
  {
    id: 'csr-1',
    name: 'CSR-1 Registration',
    category: ServiceCategory.NGO,
    shortDescription: 'Mandatory to accept Corporate CSR Funds.',
    description: 'Registration with MCA to become eligible for Corporate Social Responsibility funding from big companies.',
    price: '4,500',
    rating: 4.8,
    reviews: 1100,
    image: 'https://images.unsplash.com/photo-1554224154-26032ffc0d07?auto=format&fit=crop&q=100&w=1200',
    features: ['MCA Filing', 'Instant Certificate', 'Eligibility Check'],
    documents: ['12A/80G Copy', 'Director PAN', 'Registration Doc'],
    process: ['Filing Form', 'System Approval'],
    timeframe: '3 Days',
    validity: 'Lifetime',
    faqs: []
  },
  {
    id: 'fcra-reg',
    name: 'FCRA Registration',
    category: ServiceCategory.NGO,
    shortDescription: 'Accept Foreign Funding via MHA.',
    description: 'License from Ministry of Home Affairs to receive donations from international entities and NRIs.',
    price: '25,000',
    rating: 4.7,
    reviews: 320,
    image: 'https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?auto=format&fit=crop&q=100&w=1200',
    features: ['MHA Liaison', 'IB Inquiry Support', 'Compliance Audit'],
    documents: ['3 Year Audited Balance Sheet', 'Activity Report', 'Trustee Profile'],
    process: ['Online Application', 'IB Inquiry', 'Approval'],
    timeframe: '180 Days',
    validity: '5 Years',
    faqs: []
  },
  {
    id: 'niti-aayog',
    name: 'NITI Aayog (NGO Darpan)',
    category: ServiceCategory.NGO,
    shortDescription: 'Enlist with Central Govt Portal for Grants.',
    description: 'Registration on the NGO Darpan portal is mandatory for applying for any Central/State Govt. schemes or grants.',
    price: '2,500',
    rating: 4.9,
    reviews: 5100,
    image: 'https://images.unsplash.com/photo-1532629345422-7515f3d16bb8?auto=format&fit=crop&q=100&w=1200',
    features: ['ID Generation', 'Scheme Mapping', 'Profile Update'],
    documents: ['Trustee Details', 'Registration Cert', 'PAN of NGO'],
    process: ['Portal Signup', 'Data Entry', 'Verification'],
    timeframe: '5 Days',
    validity: 'Lifetime',
    faqs: []
  },

  // --- CORPORATE & STARTUP ---
  {
    id: 'pvt-ltd',
    name: 'Private Limited Company',
    category: ServiceCategory.CORPORATE,
    shortDescription: 'Premium Startup Incorporation with MCA.',
    description: 'Register your business as a legal private entity. Highly preferred by investors and banks.',
    price: '12,000',
    rating: 4.9,
    reviews: 6200,
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&q=100&w=1200',
    features: ['2 DSC & DIN', 'Name Approval', 'MoA/AoA'],
    documents: ['Director IDs', 'Bank Statement', 'Office Proof'],
    process: ['DSC Prep', 'SPICe+ Filing', 'Certificate'],
    timeframe: '10 Days',
    validity: 'Lifetime',
    faqs: []
  },
  {
    id: 'llp-reg',
    name: 'LLP Registration',
    category: ServiceCategory.CORPORATE,
    shortDescription: 'Hybrid of Company & Partnership.',
    description: 'Limited Liability Partnership offers the benefits of a company with the ease of a partnership firm.',
    price: '9,000',
    rating: 4.8,
    reviews: 3100,
    image: 'https://images.unsplash.com/photo-1454165833767-0274b0026739?auto=format&fit=crop&q=100&w=1200',
    features: ['Agreement Drafting', 'Partner DSC', 'ROC Filing'],
    documents: ['Partner IDs', 'Address Proof', 'Consent Letters'],
    process: ['Name Approval', 'Incorporation', 'Agreement Filing'],
    timeframe: '15 Days',
    validity: 'Lifetime',
    faqs: []
  },
  {
    id: 'opc-reg',
    name: 'One Person Company (OPC)',
    category: ServiceCategory.CORPORATE,
    shortDescription: 'Company structure for Solo Founders.',
    description: 'Single owner company with limited liability. Combines solo ownership with corporate status.',
    price: '11,000',
    rating: 4.9,
    reviews: 1800,
    image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&q=100&w=1200',
    features: ['DSC/DIN', 'Nominee Appointment', 'Certificate'],
    documents: ['Owner ID', 'Nominee ID', 'Office Proof'],
    process: ['Preparation', 'Filing', 'Approval'],
    timeframe: '10 Days',
    validity: 'Lifetime',
    faqs: []
  },
  {
    id: 'nidhi-company',
    name: 'Nidhi Company Setup',
    category: ServiceCategory.CORPORATE,
    shortDescription: 'Banking entity for member lending.',
    description: 'Form a Nidhi Company to facilitate savings and loans among members under MCA guidelines.',
    price: '35,000',
    rating: 4.6,
    reviews: 240,
    image: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&q=100&w=1200',
    features: ['Full MCA Compliance', 'Drafting', 'Compliance Plan'],
    documents: ['7 Members PAN', '3 Directors ID', 'Office NOC'],
    process: ['Name Approval', 'MoA/AoA', 'Certificate'],
    timeframe: '30 Days',
    validity: 'Lifetime',
    faqs: []
  },
  {
    id: 'microfinance',
    name: 'Microfinance Company',
    category: ServiceCategory.CORPORATE,
    shortDescription: 'Non-Banking entity for small loans.',
    description: 'Establish a Section 8 Microfinance company to provide small credit without RBI NBFC registration (within limits).',
    price: '45,000',
    rating: 4.8,
    reviews: 150,
    image: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&q=100&w=1200',
    features: ['Legal Structure', 'Compliance Advisory', 'Lending Policy'],
    documents: ['Detailed Profiles', 'Capital Proof', 'Office Docs'],
    process: ['Incorporation', 'Business Plan', 'Policies'],
    timeframe: '40 Days',
    validity: 'Lifetime',
    faqs: []
  },
  {
    id: 'startup-india',
    name: 'Startup India Recognition',
    category: ServiceCategory.CORPORATE,
    shortDescription: 'DPIIT Recognition for Govt. Benefits.',
    description: 'Get recognized by DPIIT to unlock tax holidays, IPR rebates, and priority in govt. tenders.',
    price: '5,000',
    rating: 4.9,
    reviews: 4200,
    image: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&q=100&w=1200',
    features: ['DPIIT App', 'Write-up Support', 'Benefit Guidance'],
    documents: ['Company Cert', 'Pitch Deck', 'Business Plan'],
    process: ['Portal Prep', 'Submission', 'Review'],
    timeframe: '10 Days',
    validity: '10 Years',
    faqs: []
  },

  // --- GOVT LICENSES ---
  {
    id: 'gst-reg',
    name: 'GST Registration',
    category: ServiceCategory.LICENSE,
    shortDescription: 'Mandatory Tax ID for Business.',
    description: 'Secure your GSTIN for nationwide trade, legal billing, and input tax credits.',
    price: '1,500',
    rating: 4.9,
    reviews: 12000,
    image: 'https://images.unsplash.com/photo-1554224155-1696413575b9?auto=format&fit=crop&q=100&w=1200',
    features: ['HSN Support', 'Portal Setup', 'Liaison'],
    documents: ['PAN', 'Aadhar', 'Photo', 'Electricity Bill'],
    process: ['Form Prep', 'Filing', 'Verification'],
    timeframe: '7 Days',
    validity: 'Lifetime',
    faqs: []
  },
  {
    id: 'msme-reg',
    name: 'MSME (Udyam) Registration',
    category: ServiceCategory.LICENSE,
    shortDescription: 'Priority Sector Benefits for SME.',
    description: 'Official govt certificate to get low-interest loans and priority in state procurement.',
    price: '1,000',
    rating: 4.9,
    reviews: 8900,
    image: 'https://images.unsplash.com/photo-1664575602554-2087b04935a5?auto=format&fit=crop&q=100&w=1200',
    features: ['Instant Download', 'Subsidy Mapping', 'Priority Card'],
    documents: ['Aadhar', 'PAN'],
    process: ['Online Filing', 'OTP Verification'],
    timeframe: '1 Day',
    validity: 'Lifetime',
    faqs: []
  },
  {
    id: 'fssai-lic',
    name: 'FSSAI (Food License)',
    category: ServiceCategory.LICENSE,
    shortDescription: 'Mandatory for all Food Businesses.',
    description: 'Whether NGO kitchen or Corporate cafeteria, FSSAI is mandatory for food safety compliance.',
    price: '3,000',
    rating: 4.8,
    reviews: 4500,
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&q=100&w=1200',
    features: ['State/Central/Basic', 'Safety Plan', 'Renewal Alerts'],
    documents: ['Photo', 'Layout Plan', 'List of Food'],
    process: ['Declaration', 'Inspection (if req)', 'Issuance'],
    timeframe: '15 Days',
    validity: '5 Years',
    faqs: []
  },
  {
    id: 'iec-reg',
    name: 'Import Export Code (IEC)',
    category: ServiceCategory.LICENSE,
    shortDescription: 'License for Global Trade.',
    description: 'Mandatory code for any business or NGO looking to import goods or export services globally.',
    price: '2,500',
    rating: 4.9,
    reviews: 2100,
    image: 'https://images.unsplash.com/photo-1578575437130-527eed3abbec?auto=format&fit=crop&q=100&w=1200',
    features: ['DGFT Liaison', 'Lifetime Validity', 'Auto-Approval'],
    documents: ['PAN', 'Cancel Cheque', 'Office Proof'],
    process: ['DGFT Filing', 'Verification'],
    timeframe: '3 Days',
    validity: 'Lifetime',
    faqs: []
  },
  {
    id: 'iso-9001',
    name: 'ISO 9001:2015 Cert',
    category: ServiceCategory.LICENSE,
    shortDescription: 'Global Quality Management Standard.',
    description: 'Boost your brand credibility and process efficiency with ISO certification. Mandatory for many tenders.',
    price: '6,500',
    rating: 4.8,
    reviews: 3200,
    image: 'https://images.unsplash.com/photo-1560179707-f14e90ef3623?auto=format&fit=crop&q=100&w=1200',
    features: ['Accredited Cert', 'Audit Support', 'Documentation'],
    documents: ['Profile', 'Flowchart', 'Product/Service List'],
    process: ['Audit', 'Correction', 'Certification'],
    timeframe: '10 Days',
    validity: '3 Years',
    faqs: []
  },

  // --- IPR & TRADEMARK ---
  {
    id: 'tm-reg',
    name: 'Trademark Registration',
    category: ServiceCategory.IPR,
    shortDescription: 'Protect your Brand Name & Logo.',
    description: 'Legal protection against identity theft. Get the power of (TM) and (R) symbols.',
    price: '3,500',
    rating: 4.9,
    reviews: 7800,
    image: 'https://images.unsplash.com/photo-1589254065878-42c9da997008?auto=format&fit=crop&q=100&w=1200',
    features: ['Search Report', 'Class Selection', 'Response to Objections'],
    documents: ['Logo', 'MSME Certificate', 'Power of Attorney'],
    process: ['Search', 'Filing', 'Examination'],
    timeframe: '12 Months',
    validity: '10 Years',
    faqs: []
  },
  {
    id: 'copyright-reg',
    name: 'Copyright Registration',
    category: ServiceCategory.IPR,
    shortDescription: 'Protect Creative Work & Content.',
    description: 'Secure legal rights for your artistic, literary, or musical works including website content and software code.',
    price: '4,000',
    rating: 4.8,
    reviews: 1400,
    image: 'https://images.unsplash.com/photo-1560523160-754a9e25c68f?auto=format&fit=crop&q=100&w=1200',
    features: ['Legal Drafting', 'NOC Prep', 'Department Follow-up'],
    documents: ['Soft Copy', 'ID Proof', 'Author Profile'],
    process: ['Diary Number', 'Wait Period', 'Grant'],
    timeframe: '8 Months',
    validity: 'Lifetime (Author + 60yrs)',
    faqs: []
  },

  // --- TECH & DIGITAL ---
  {
    id: 'ngo-website',
    name: 'NGO Impact Website',
    category: ServiceCategory.TECH,
    shortDescription: 'HD Website with Donation Gateway.',
    description: 'Professional, mobile-responsive website tailored for NGOs. Includes donation buttons and volunteer forms.',
    price: '12,500',
    rating: 4.9,
    reviews: 840,
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&q=100&w=1200',
    features: ['Donation Gateway', 'SEO Optimized', 'CMS Support'],
    documents: ['Logo', 'Trust Info', 'Photos'],
    process: ['Design', 'Development', 'Hosting'],
    timeframe: '15 Days',
    validity: 'Annual Renewal',
    faqs: []
  },
  {
    id: 'corp-website',
    name: 'Corporate Web Presence',
    category: ServiceCategory.TECH,
    shortDescription: 'Premium High-Perf Business Website.',
    description: 'Elite digital identity for corporations. Modern design, lightning-fast speed, and enterprise security.',
    price: '18,000',
    rating: 4.9,
    reviews: 620,
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=100&w=1200',
    features: ['Enterprise Security', 'Premium Hosting', 'Analytics'],
    documents: ['Profile', 'Services list', 'Branding'],
    process: ['Consult', 'Wireframe', 'Build'],
    timeframe: '20 Days',
    validity: 'Annual Renewal',
    faqs: []
  },
  {
    id: 'dsc-cert',
    name: 'Digital Signature (DSC)',
    category: ServiceCategory.TECH,
    shortDescription: 'Class 3 DSC for E-Filing.',
    description: 'Certified digital signatures for MCA, GST, Income Tax, and Tenders.',
    price: '1,500',
    rating: 4.9,
    reviews: 15000,
    image: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&q=100&w=1200',
    features: ['Class 3 Signing', 'USB Token', 'Instant Video KYC'],
    documents: ['PAN', 'Aadhar', 'Mobile (linked)'],
    process: ['KYC', 'Approval', 'Download'],
    timeframe: '2 Hours',
    validity: '2 Years',
    faqs: []
  },

  // --- FINANCE & TAX ---
  {
    id: 'ngo-audit',
    name: 'NGO Annual Audit',
    category: ServiceCategory.FINANCE,
    shortDescription: 'Statutory Audit by Chartered Accountants.',
    description: 'Maintain compliance with Income Tax and Registrar. Expert auditing for 12A/80G maintenance.',
    price: '10,000',
    rating: 4.8,
    reviews: 1900,
    image: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&q=100&w=1200',
    features: ['CA Certified', 'Balance Sheet Prep', 'Tax Audit Report'],
    documents: ['Bank Statements', 'Vouchers', 'Prev Balance Sheet'],
    process: ['Data Review', 'Drafting', 'Sign-off'],
    timeframe: '20 Days',
    validity: 'Annual',
    faqs: []
  },
  {
    id: 'roc-filing',
    name: 'Annual ROC Compliance',
    category: ServiceCategory.FINANCE,
    shortDescription: 'Maintain Active Status for Companies.',
    description: 'Mandatory annual filing of AOC-4 and MGT-7 with MCA. Avoid heavy penalties and disqualification.',
    price: '8,000',
    rating: 4.9,
    reviews: 3200,
    image: 'https://images.unsplash.com/photo-1454165833767-0274b0026739?auto=format&fit=crop&q=100&w=1200',
    features: ['Statutory Records', 'MCA E-Filing', 'Compliance Check'],
    documents: ['Financials', 'Director Consent', 'DSC'],
    process: ['Board Meeting', 'Filing', 'Approval'],
    timeframe: '15 Days',
    validity: 'Annual',
    faqs: []
  }
];

export const CATEGORIES = Object.values(ServiceCategory);
