
import { Service, ServiceCategory } from './types';

export const SERVICES: Service[] = [
  {
    id: '12a-80g',
    name: '12A & 80G Registration',
    category: ServiceCategory.NGO,
    shortDescription: 'Tax exemption for NGOs and benefits for high-value donors.',
    description: 'Ensure your NGO income is 100% tax-exempt under Section 12A and provide 50% tax deductions to your donors under Section 80G. This is the cornerstone of trust compliance and mandatory for receiving Corporate Social Responsibility (CSR) funds.',
    price: '15,000',
    rating: 4.9,
    reviews: 2450,
    image: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&q=100&w=2000',
    features: ['Form 10A Professional Filing', 'Departmental Liaison & Queries', '5-Year Compliance Guarantee', 'Expert Audit Support'],
    documents: ['Registration Certificate', 'Trust Deed / MOA', '3-Year Audit Reports', 'NOC from Landlord'],
    process: ['Initial Audit', 'Portal Submission', 'Departmental Review', 'Issuance of Final Order'],
    timeframe: '45-60 Days',
    validity: '5 Years',
    faqs: [
      { question: "Is 80G registration lifetime?", answer: "No, currently registrations under 12A and 80G are granted for a period of 5 years and require renewal." }
    ]
  },
  {
    id: 'ngo-reg',
    name: 'NGO Registration (Trust/Society)',
    category: ServiceCategory.NGO,
    shortDescription: 'Professional Trust, Society, or Section 8 Company formation.',
    description: 'Expert legal assistance in drafting Trust Deeds, Society Bye-laws, and Incorporation of Section 8 companies with full MCA and Sub-registrar compliance.',
    price: '8,500',
    rating: 4.8,
    reviews: 1820,
    image: 'https://images.unsplash.com/photo-1532629345422-7515f3d16bb8?auto=format&fit=crop&q=100&w=2000',
    features: ['Deed Drafting by Advocates', 'Registration in Sub-registrar Office', 'PAN/TAN Application', 'NITI Aayog Enrollment'],
    documents: ['ID Proofs of Trustees', 'Address Proofs', 'NOC for Registered Office'],
    process: ['Drafting', 'Stamp Duty Payment', 'Appointment with Registrar', 'Registration'],
    timeframe: '15 Days',
    validity: 'Lifetime',
    faqs: []
  },
  {
    id: 'pvt-ltd',
    name: 'Private Limited Company',
    category: ServiceCategory.CORPORATE,
    shortDescription: 'The gold standard for high-growth startups and businesses.',
    description: 'Establish your brand as a legal entity. We handle DIN, DSC, MOA, and AOA drafting for a seamless incorporation experience under MCA.',
    price: '12,000',
    rating: 4.9,
    reviews: 3100,
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=100&w=2000',
    features: ['2 DIN & DSC Included', 'MOA/AOA Custom Drafting', 'Startup India Eligibility Check', 'Certificate of Incorporation'],
    documents: ['PAN & Aadhar', 'Bank Statement', 'Electricity Bill of Office'],
    process: ['Name Reservation (RUN)', 'Digital Signature Issuance', 'SPICe+ Filing', 'Final Approval'],
    timeframe: '10 Days',
    validity: 'Lifetime',
    faqs: []
  },
  {
    id: 'fcra',
    name: 'FCRA Registration',
    category: ServiceCategory.NGO,
    shortDescription: 'Mandatory to accept foreign contributions via MHA.',
    description: 'Foreign Contribution Regulation Act registration is essential for any NGO that intends to receive funds from international donors.',
    price: '25,000',
    rating: 4.7,
    reviews: 340,
    image: 'https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?auto=format&fit=crop&q=100&w=2000',
    features: ['Prior Permission or Registration', 'MHA Liaisoning', 'Compliance Reporting'],
    documents: ['3-Year Audit Report', 'Activity Report', 'Trustee Credentials'],
    process: ['Documentation', 'Application Filing', 'Intelligence Bureau Inquiry', 'Grant'],
    timeframe: '180 Days',
    validity: '5 Years',
    faqs: []
  },
  {
    id: 'trademark',
    name: 'Trademark Registration',
    category: ServiceCategory.IPR,
    shortDescription: 'Protect your brand name, logo, and intellectual identity.',
    description: 'Legal protection against brand infringement. Secure the "TM" and "R" symbols for your unique brand identity.',
    price: '2,500',
    rating: 4.9,
    reviews: 2900,
    image: 'https://images.unsplash.com/photo-1589254065878-42c9da997008?auto=format&fit=crop&q=100&w=2000',
    features: ['Brand Search Report', 'Class Selection Advice', 'Response to Objections'],
    documents: ['Logo Artwork', 'Power of Attorney', 'User Affidavit'],
    process: ['Trademark Search', 'Application Filing', 'Examination', 'Publication'],
    timeframe: '8-12 Months',
    validity: '10 Years',
    faqs: []
  },
  {
    id: 'gst-reg',
    name: 'GST Registration',
    category: ServiceCategory.FINANCE,
    shortDescription: 'Mandatory tax identification for modern businesses.',
    description: 'Secure your Goods and Services Tax Identification Number (GSTIN) to participate in national commerce.',
    price: '2,000',
    rating: 4.9,
    reviews: 6400,
    image: 'https://images.unsplash.com/photo-1554224155-1696413575b9?auto=format&fit=crop&q=100&w=2000',
    features: ['GST Portal Setup', 'HSN/SAC Code Selection', 'Liaison with GST Officer'],
    documents: ['PAN of Entity', 'Proof of Premises', 'Authorized Signatory Details'],
    process: ['Application submission', 'Verification of docs', 'Approval'],
    timeframe: '7 Days',
    validity: 'Lifetime',
    faqs: []
  },
  {
    id: 'fssai',
    name: 'FSSAI (Food License)',
    category: ServiceCategory.LICENSE,
    shortDescription: 'Official food safety certificate for all food businesses.',
    description: 'Whether you are a retailer, manufacturer, or NGO running a kitchen, FSSAI is mandatory to ensure food safety standards.',
    price: '3,500',
    rating: 4.8,
    reviews: 3100,
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&q=100&w=2000',
    features: ['State/Central/Registration', 'Food Safety Plan', 'Annual Compliance'],
    documents: ['Photo of Business', 'Layout Plan', 'List of Food Category'],
    process: ['Form selection', 'Upload docs', 'Inspection (if req)', 'License'],
    timeframe: '15 Days',
    validity: '5 Years',
    faqs: []
  },
  {
    id: 'nidhi-co',
    name: 'Nidhi Company Setup',
    category: ServiceCategory.CORPORATE,
    shortDescription: 'Mutual benefit society for internal lending.',
    description: 'Establish a Nidhi Company to facilitate savings and internal lending for your members under MCA guidelines.',
    price: '35,000',
    rating: 4.7,
    reviews: 140,
    image: 'https://images.unsplash.com/photo-1454165833767-0274b0026739?auto=format&fit=crop&q=100&w=2000',
    features: ['NDH-1 & NDH-3 Filings', 'Savings Scheme Planning', 'Lending Policy Drafting'],
    documents: ['7 Minimum Members PAN', '3 Directors ID', 'Office NOC'],
    process: ['Name Approval', 'MoA/AoA', 'Incorporation'],
    timeframe: '25 Days',
    validity: 'Lifetime',
    faqs: []
  },
  {
    id: 'msme',
    name: 'MSME (Udyam) Registration',
    category: ServiceCategory.LICENSE,
    shortDescription: 'Unlock priority sector lending and government subsidies.',
    description: 'Register your enterprise on the Udyam portal to become eligible for various MSME benefits including interest rate subsidies.',
    price: '1,500',
    rating: 4.9,
    reviews: 5200,
    image: 'https://images.unsplash.com/photo-1664575602554-2087b04935a5?auto=format&fit=crop&q=100&w=2000',
    features: ['Instant Registration', 'Priority Lending Benefits', 'Govt Subsidies Access'],
    documents: ['Aadhar Linked with Mobile', 'PAN of Business'],
    process: ['Online Application', 'Data Verification', 'E-Certificate'],
    timeframe: '2 Days',
    validity: 'Lifetime',
    faqs: []
  },
  {
    id: 'website-dev',
    name: 'Premium Corporate Website',
    category: ServiceCategory.TECH,
    shortDescription: 'HD digital presence for NGOs and Corporates.',
    description: 'High-performance, mobile-responsive websites designed for impact and professional trust.',
    price: '15,000',
    rating: 4.9,
    reviews: 420,
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&q=100&w=2000',
    features: ['CMS Integration', 'Secure Hosting', 'SEO Optimized'],
    documents: ['Logo', 'Content', 'Brand Colors'],
    process: ['Wireframing', 'Design', 'Development', 'Launch'],
    timeframe: '15 Days',
    validity: 'Annual Renewal',
    faqs: []
  },
  {
    id: 'legal-advisory',
    name: 'Custom Legal Advisory',
    category: ServiceCategory.OTHER,
    shortDescription: 'Direct consultation with Advocate Tamanna.',
    description: 'Bespoke legal solutions for complex litigation, drafting of contracts, or strategic compliance planning.',
    price: '5,000',
    rating: 4.9,
    reviews: 1500,
    image: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&q=100&w=2000',
    features: ['1-on-1 Zoom Consult', 'Written Opinion', 'Strategy Deck'],
    documents: ['Case History', 'Existing Contracts'],
    process: ['Case Review', 'Scheduling Call', 'Opinion Delivery'],
    timeframe: 'Varies',
    validity: 'Project Based',
    faqs: []
  }
];

export const CATEGORIES = Object.values(ServiceCategory);
